[[pages]]
name = "Introduction"
icon = "👋"
path = "introduction.py"
url_path = "introduction"

[[pages]]
name = "Architecture"
icon = "🏗️"
path = "architecture.py"
url_path = "architecture"

[[pages]]
name = "Demo"
icon = "📕"
is_section = true

[[pages]]
name = "Step 1 - Process Interactions"
icon = "🔋"
path = "process_interactions.py"
url_path = "process_interactions"

[[pages]]
name = "Step 2 - Filter Complaints"
icon = "↪️"
path = "filter_complaints.py"
url_path = "process_complaints"

[[pages]]
name = "Step 3 - View Complaints Dashboard"
icon = "📊"
path = "view_complaints_dashboard.py"
url_path = "view_complaints_dashboard"

[[pages]]
name = "Options"
icon = "🛠️"
is_section = true

[[pages]]
name = "Model Settings"
icon = "🤖"
path = "settings.py"
url_path = "settings"

[[pages]]
name = "Prompts"
icon = "📌"
path = "prompts.py"
url_path = "prompts"